### ISSUE TITLE
Python Contribution.

### ISSUE THREAD

**Issue by lxmn22nov** [akscoder082003/Leetcode_Solutions#3]
Anyone who is open to solve the Leetcode questions, solution to this repository.

**Comment by RaghavBansal-18** [comment]
yes and what will i have to do?

**Comment by akscoder082003** [comment]
Okk

**Comment by lxmn22nov** [comment]
Simply fork the repo, clone it locally, make folder namely **Python** and add solution in it with question commented.
push it to forked repo, compare and create PR. then we will merge it.

**Comment by RaghavBansal-18** [comment]
And one more thing what type of questions?

**Comment by RaghavBansal-18** [comment]
Any leetcofe question on python?

**Comment by lxmn22nov** [comment]
yes, only leetcode questions solution in python.
